### PR TITLE
ArrayTrie loading time optimization

### PR DESCRIPTION
**Pull request by dmit25**
**First of all, thanks a lot for such a great projects (CRF#, RNN#, etc.)**
Short description:
Major ArrayTrie loading time optimization (using buffered read)
Environment: SSD + 45Mb .feature file
baseline: ~ 570ms
updated: ~ 180ms
- gitignore file

### CODE REVIEW

**Comment by dmit25** [comment]
@zhongkaifu Hi! What do you think about this PR?

**Comment by zhongkaifu** [comment]
@dmit25  Thanks for your improvement. The result is pretty good. The code change looks good, did you already test it completely ? Sorry that I don't have enough time for testing yet.

**Comment by dmit25** [comment]
@zhongkaifu Sure, fully tested (training, evaluation, etc.), deployed in production.

**Comment by zhongkaifu** [comment]
Cool. The change list has been merged. Thanks for your contribution.

**Pull request merged**
